### ISSUE TITLE
Swingwallet does not create zero.conf

### ISSUE THREAD

**Issue by zzzpotato** [LEAD-Anoy74/SwingWallet#1]
On fresh installs, zero.conf does not get created in %appdata%/ZeroClassic and throws the following error.

![screenshot_31](https://user-images.githubusercontent.com/35818234/45920381-d2f5cb00-be68-11e8-9c75-e770cca95ee1.jpg)

A quick remedy is making the file yourself.

**Comment by LEAD-Anoy74** [comment]
SwingWallet just act as a GUI software for ZeroClassic daemon, it doesn't create it automatically. Either you can create one by hand or just use SimpleWallet.
